### ISSUE TITLE
Yoga 7 14IAL7

### ISSUE THREAD

**Issue by bbascarevic** [PJungkamp/yoga9-linux#3]
It seems that the sound patch for Yoga 9 works also for Yoga 7 14IAL7, only the device ID needs to be added (`0x17aa, 0x3869`). I tested it on my Yoga 7 as a DKMS module and it works (Arch Linux 5.19). There was no need to blacklist any modules or pass any module options, only `sof-firmware` package needed to be installed.

Would you be ok with me publishing the DMKS module on GitHub as an interim solution, until your patches make it to next kernel version? Or alternatively would you be willing to add DKMS packaging to this repo (anything to avoid recompiling the kernel on every update :) )?

Thank you very much for providing these patches.

**Comment by pjungkamp** [comment]
Feel free to use this stuff.

The modprobe.d file is for those who want to try the patch without modifying it.

It seems like it's going to be included in the 5.18 and 5.19 stable trees, so you could use a stable prebuilt kernel with the modprobe file as an interim solution.
