### ISSUE TITLE
Little guide for the pathing process

### ISSUE THREAD

**Issue by balalamba** [PJungkamp/yoga9-linux#4]
Hello Philipp, 
Thank you very much for putting together the necessary fixes in patches!
I've just received my Yoga and I'm trying to fix all problems.
I don't have enough experience in linux to be sure that I doing that correctly, so can you update your readme and write some useful information about how to patch linux kernel in our case ? 
Thanks!

**Comment by pjungkamp** [comment]
The easiest patching process probably depends on your distribution's package manager. Or you install it manually using `make`.

So first of all, what distro are you using?

**Comment by sidevesh** [comment]
hey @PJungkamp and @olegpopovskiy , I am also working through fixing all issues with my recently purchased Yoga 7 14ACN6 laptop, which is also a convertible.
I was wondering if the patch for the shortcut keys (The Star with S and the others, the Star one is the only one present in my laptop) were submitted to mainline ?
I saw some discussion regarding figuring out how to get it to mainline but didn't see any updates about it on the thread about it.

**Comment by sidevesh** [comment]
Oh, and I am also using Arch  as you @PJungkamp so a simple write up the process would help me out too :)

**Comment by pjungkamp** [comment]
I've only submitted the Audio patch until now.
I was busy with my exams.

Did you check out the README in the `packaging/arch/` directory?

**Comment by pjungkamp** [comment]
Small update. I was offline for most of September and October. The fn-key patches are on their way to mainline.

**Comment by sidevesh** [comment]
Thanks @PJungkamp , saw the discussion on the mailing lists about the fn-keys patch getting into the mainline, great work!
Also saw that the ideapad-laptop not exposing rapid charge issue's fix didnt make it through, I am thinking of creating a gnome extension or adding support for it in an existing Ideapad controls gnome extension in the meantime by making direct acpi calls,
we have https://aur.archlinux.org/packages/ideapad-wmi-fn-keys-dkms-git for enabling the fn keys in the meantime till the mainline support gets released,
I have also made a dkms module from your usage mode patch that is available at https://aur.archlinux.org/packages/ideapad-wmi-usage-mode-dkms-git (doesn't work for me though yet)
Only thing remaining atleast for my laptop (Yoga 7 14ACN6) is exposing the keyboard backlight controls,
and the fingerprint sensor but that's a whole other issue.

**Comment by pjungkamp** [comment]
I already know how to configure the keyboard backlight via `acpi_call`. I just haven't bothered to write a patch for that yet.

The parameter values needed to control the keyboard backlight on my Yoga can be found here:
https://github.com/PJungkamp/yoga9-linux/tree/main/acpi-dump#readme

The basic idea is:
1. Store the type of keyboard backlight [here](https://github.com/torvalds/linux/blob/01f856ae6d0ca5ad0505b79bf2d22d7ca439b2a1/drivers/platform/x86/ideapad-laptop.c#L145-L149).
2. Set keyboard type to `KBLC` and `kbd_bl` to `1` if the function is found on the `adev` [here](https://github.com/torvalds/linux/blob/01f856ae6d0ca5ad0505b79bf2d22d7ca439b2a1/drivers/platform/x86/ideapad-laptop.c#L1584-L1623).
3. Adapt [this code](https://github.com/torvalds/linux/blob/01f856ae6d0ca5ad0505b79bf2d22d7ca439b2a1/drivers/platform/x86/ideapad-laptop.c#L1312-L1412) to call the `KBLC` acpi function if it is present.
4. ...
5. $$ profit $$

I noticed that it's also possible to get notifications when the backlight changes automatically.
That's the `Dynamic KB Lighting` sensor in the [`sensors.txt`](https://github.com/PJungkamp/yoga9-linux/blob/main/intel-ish/sensors.txt). But it's an Intel sensor again. Probably no use on AMD.

**Comment by stuarthayhurst** [comment]
@PJungkamp 

I've got the Yoga 7 AMD `14ARB7`, and the backlight control seems to be `\_SB.PCI0.LPC0.EC0.VPC0.KBLC` on my laptop. Sadly the values you have in your table don't do anything for mine, so I was wondering how you came across them? Hopefully the only difference is the argument required :)

**Comment by pjungkamp** [comment]
I read the ACPI tables, reverse-engineering what input would result in a code path in the ASL that seemed somewhat promising...

You could also try tracing the ACPI calls Windows is doing.

It's somewhat difficult either way.
As you're poking around in your firmware's memory you should also be careful. You could easily trigger slumbering bugs in unused code paths.

I mostly noted the KBLC commands that did the trick for me as a note to myself. I just didn't have any motivation to build a driver for a feature that's a shortcut away.

**Comment by stuarthayhurst** [comment]
Thanks for the info. I'll probably leave it for now then, as I have 101 other problems to fix that don't involve prodding the firmware.
