### ISSUE TITLE
WMI driver emits KEY_UNKNOWN

### ISSUE THREAD

**Issue by soyersoyer** [PJungkamp/yoga9-linux#7]
Thanks for these patches.
The WMI driver emits KEY_UNKNOWN if you press the fn+esc the second time.
The
```
+	{ KE_IGNORE,	0x03 },
```
fixes that.

**Comment by pjungkamp** [comment]
Fixed in the latest revision of the patch I submitted. It's on its way to mainline. I would have missed that without your comment. Thank you!
