### ISSUE TITLE
Patch not working on Lenovo Yoga 7 Gen 7 AMD (14ARB7)

### ISSUE THREAD

**Issue by 64kramsystem** [PJungkamp/yoga9-linux#8]
I'm opening this issue just for reference (in case somebody with the same device is looking for a solution).

I've tried to force the [bass speaker fix](https://github.com/PJungkamp/yoga9-linux/blob/main/config/etc/modprobe.d/snd.conf) on my device (Yoga 7 Gen 7 AMD (14ARB7)), but it didn't yield any effect:

```sh
# rebooted after this change
#
sudo tee /etc/modprobe.d/snd.conf <<CONF
options snd_intel_dspcfg dsp_driver=1
options snd_hda_intel model=alc287-yoga9-bass-spk-pin
CONF
```

This has been tested on a v6.0-rc7 kernel, without any patch (actually, I've applied the [mic fix](https://bugzilla.kernel.org/show_bug.cgi?id=216299#c3), which I think should not be in conflict), since I've seen that the patches in this repository have been upstreamed.

**Comment by tikkel** [comment]
My würgaround...

/root/bass-speaker-on.sh
#!/usr/bin/env bash
/usr/sbin/i2cset -y 3 0x48 0x2 0
/usr/sbin/i2cset -y 3 0x48 0x3 0

/etc/systemd/system/customboot.service 
[Unit]
Description=Custom Bootup Script
After=tlp.service
[Service]
ExecStart=/root/bass-speaker-on.sh
[Install]
WantedBy=default.target

/etc/tlp.conf
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=0
SOUND_POWER_SAVE_CONTROLLER=N

**Comment by 64kramsystem** [comment]
> My würgaround...
> 
> /root/bass-speaker-on.sh #!/usr/bin/env bash /usr/sbin/i2cset -y 3 0x48 0x2 0
> 
> /etc/systemd/system/customboot.service [Unit] Description=Custom Bootup Script After=tlp.service [Service] ExecStart=/root/bass-speaker-on.sh [Install] WantedBy=default.target
> 
> /etc/tlp.conf SOUND_POWER_SAVE_ON_AC=0 SOUND_POWER_SAVE_ON_BAT=0 SOUND_POWER_SAVE_CONTROLLER=N

Wow, it works 🤯 Many thanks :smile: 

Here's a script, for anybody who wanted to just copy/paste. It assumes that tlp is installed and *enabled*.

```sh
# to run as root

apt install -y i2c-tools

cat > /etc/tlp.d/99_fix_yoga_speakers.conf << 'CONF'
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=0
SOUND_POWER_SAVE_CONTROLLER=N
CONF

systemctl restart tlp

cat > /root/bass-speaker-on.sh << 'SH'
#!/usr/bin/env bash
/usr/sbin/i2cset -y 3 0x48 0x2 0
SH

chmod 755 /root/bass-speaker-on.sh

cat > /etc/systemd/system/customboot.service << 'UNIT'
[Unit]
Description=Custom Bootup Script
After=tlp.service
[Service]
ExecStart=/root/bass-speaker-on.sh
[Install]
WantedBy=default.target
UNIT

systemctl daemon-reload
systemctl enable --now customboot
```

**Comment by soupglasses** [comment]
Do you still run it with the `snd.conf` modprobe? Or have you removed that section before running these steps?

**Comment by 64kramsystem** [comment]
> Do you still run it with the `snd.conf` modprobe? Or have you removed that section before running these steps?

I've just run it successfully, and I think this workaround works in isolation; I don't think I've previously applied other related changes - I've rolled back the `snd.conf` change after I found that it didn't work.

I was, rather, surprised that `tlp` is preinstalled; I think that on Ubuntu they started to preinstall it only recently (verified on 22.04 as dependency of the desktop package).

**Comment by 64kramsystem** [comment]
This workaround needs a refinement - the `ic2set` command needs to be rerun after resuming (works on resume from hibernation; didn't test from suspend):

```sh
cat > /lib/systemd/system-sleep/fix_yoga_speakers << 'SH'
#!/bin/bash

if [[ $1 == "post" ]]; then
  /root/bass-speaker-on.sh
fi
SH

chmod +x /lib/systemd/system-sleep/fix_yoga_speakers
```

**Comment by tikkel** [comment]
So, I didn't set any modprobes.
I reinstalled TLP.
apt install tlp
edit: /etc/tlp.conf
systemctl enable tlp
systemctl start tlp

Still important!
The speaker may be driven with too much power!
Therefore set another register, which reduces the power/volume. Better safe than sorry.
(https://bugzilla.kernel.org/show_bug.cgi?id=208555#c695)

/root/bass-speaker-on.sh
#!/usr/bin/env bash
/usr/sbin/i2cset -y 3 0x48 0x2 0
/usr/sbin/i2cset -y 3 0x48 0x3 0

**Comment by tikkel** [comment]
disable sound-powermanagement without tlp.service

/etc/modprobe.d/alsa-base.conf
options snd_hda_intel power_save=0 power_save_controller=N

**Comment by 64kramsystem** [comment]
> disable sound-powermanagement without tlp.service
> 
> /etc/modprobe.d/alsa-base.conf options snd_hda_intel power_save=0 power_save_controller=N

This works; note that the `customboot` service is still needed, including the `tlp` dependency (`After=...`).

**Comment by tikkel** [comment]
disable sound-powermanagement
and activate the bass speaker
simpler version
without tlp.service
my system: 
lenovo yoga7 14arb7
ubuntu 22.10 mainline-kernel 6.0
(https://kernel.ubuntu.com/~kernel-ppa/mainline/daily/2022-10-03/)


sudo su

/etc/systemd/system/yoga7-bass-speaker-on.service 
[Unit]
Description=yoga7 bass speaker on
After=pipewire.service
[Service]
ExecStart=/bin/bash -c '/usr/sbin/i2cset -y 3 0x48 0x2 0 && /usr/sbin/i2cset -y 3 0x48 0x3 0'
[Install]
WantedBy=pipewire.target

/etc/modprobe.d/alsa-base.conf
options snd_hda_intel power_save=0 power_save_controller=N

systemctl daemon-reload
systemctl enable yoga7-bass-speaker-on.service 
reboot

**Comment by pjungkamp** [comment]
The mentioned https://github.com/tomsom/yoga-linux/ repo is probably a better place to discuss problems relating to AMD Yogas. Closing this as I'm not able to fix for a device I don't own.

**Comment by soupglasses** [comment]
Current audio issues with the 14ARB7 is tracked in this issue for ease of access: https://github.com/tomsom/yoga-linux/issues/3
