### ISSUE TITLE
Ideapad usage mode patch did not work on Yoga 7 14ACN6

### ISSUE THREAD

**Issue by sidevesh** [PJungkamp/yoga9-linux#9]
I took the https://github.com/PJungkamp/yoga9-linux/blob/main/kernel-patches/0005-Add-IdeaPad-Usage-Mode-driver.patch and made it a dkms module and installed it, after that I could see the usage mode device in `evtest` but it did not emit any events on switching device modes and hence gnome also did not detect when switching to tablet mode.
I had submitted the module to arch aur at https://aur.archlinux.org/packages/ideapad-wmi-usage-mode-dkms-git, just an fyi.

**Comment by pjungkamp** [comment]
Very nice (I have no clue how to setup dkms). I'll certainly try it! What exact model do you own? I'd like to check whether the patch could work for you!

**Comment by pjungkamp** [comment]
My bad. Totally missed the title of the issue. I'd need to have a look into your DSDT table. See https://wiki.archlinux.org/title/DSDT

Please do me a favor and disassemble it using `iasl -d` before attaching it.

**Comment by sidevesh** [comment]
[dsdt.dsl.zip](https://github.com/PJungkamp/yoga9-linux/files/10097733/dsdt.dsl.zip)
No issues, and thanks again for working on this.

**Comment by pjungkamp** [comment]
The functions WMI metadata and MOF in your DSDT are exactly like mine.

Could you enable dynamic debug for the usage mode driver with `echo 'file ideapad-wmi-usage-mode.c +p' | sudo tee /sys/kernel/debug/dynamic_debug/control` and check your syslog for `WMI report scancode` lines from the usage mode driver.

If there are non of those there should at least be warnings by the driver.
If there is no output at all, no events are delivered to the driver.

**Comment by pjungkamp** [comment]
After I tinkered with the WMI devices of this laptop I checked out the the custom HID sensors. Could you also paste the result of `fish intel-ish/find_sensors.fish`. The data of the WMI device seems to be based one one of those sensors' values.

For me it looks like this:
```
Sensor: /sys/bus/ishtp/devices/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0004/HID-SENSOR-2000e1.14.auto
	Serial Number:	 LUID:0300000000000000
	Sensor Model:	 Model 
	Manufacturer:	 INTEL
	Friendly Name:	 Lid Mode Sensor
```

**Comment by sidevesh** [comment]
My model uses AMD 5800U, so I don't think this would work.

**Comment by pjungkamp** [comment]
That makes sense. Intel has an 'Integrated Sensor Hub' solution for mobile devices that enables preprocessing of sensordata in the firmware. This is used for the usage mode, presence detection and backlight adjustment. I don't know how Lenovo implements these things on the AMD side. Do you have the 'Usage modes' (Laptop/Tablet/Tent) in Vantage on windows?

**Comment by sidevesh** [comment]
I don't recall exactly, but I do know that it was able to detect tablet mode when folded backwards and disable keyboard and trackpad as well as adjust the UI on Windows taskbar etc.

**Comment by pjungkamp** [comment]
You'd have to search through your devices (e.g. in sysfs) and check whether there are multiple standard accelerometers or custom devices where Lenovo may hide the second accelerometer.
I don't have an AMD machine so I can't check. And it seems like the WMI driver is tied to Intel.

I don't even want to mainline the usage-mode driver it was more of a temporary fix. The proper solution would be to find the second accelerometer or custom sensor and get it to work in `iio-sensor-proxy`. See for example https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/merge_requests/338

I'm closing this issue for now.
